---
- hosts: 
# Example from Ansible Playbooks
#- copy: src=/etc/tower/ dest=/etc/foo.conf owner=foo group=foo mode=0644

# Note: These examples do not set authentication details, see the AWS Guide for details.

# Basic provisioning example
- ec2:
    key_name: 7165-2307-6871-keypair.ppk
    instance_type: t2.micro
    image: ami-9abea4fb
    wait: yes
    group: webserver
    count: 1
    vpc_subnet_id: subnet-da629cbf
    assign_public_ip: yes